# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=web.models.upload_location)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=web.models.upload_location)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=web.models.upload_location)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=web.models.upload_location)),
            ],
        ),
    ]
