# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link1_link',
            field=models.CharField(blank=True, help_text="Make sure the link starts with 'https://'", max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='link1_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='link2_link',
            field=models.CharField(blank=True, help_text="Make sure the link starts with 'https://'", max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='link2_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
