# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20160831_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link1_title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='link2_title',
            field=models.TextField(default=''),
        ),
    ]
