# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20160910_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='link2_title',
            new_name='link1_link',
        ),
    ]
