# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20160910_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link1_link',
            field=models.CharField(help_text="Make sure the link starts with 'https://'", max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='link1_title',
            field=models.CharField(max_length=100),
        ),
    ]
