# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20160910_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width_field',
        ),
    ]
