# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 03:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20160910_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name2',
            field=models.CharField(default=datetime.datetime(2016, 9, 11, 3, 39, 57, 727029, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
