# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_product_link2_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link2_link',
            field=models.TextField(default='', help_text="Make sure the link starts with 'https://'"),
        ),
    ]
