# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-11 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_product_link2_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name2',
        ),
        migrations.AlterField(
            model_name='product',
            name='link1_link',
            field=models.CharField(blank=True, help_text="Make sure the link starts with 'https://'", max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='link1_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='link2_link',
            field=models.CharField(blank=True, help_text="Make sure the link starts with 'https://'", max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='link2_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
