# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=web.models.upload_location),
        ),
    ]
