# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_announcement_image4'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
