# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-30 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
