# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 01:55
from __future__ import unicode_literals

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20160830_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=reviews.models.upload_location)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=reviews.models.upload_location)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=reviews.models.upload_location)),
            ],
        ),
        migrations.AlterField(
            model_name='wine',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=reviews.models.upload_location, width_field='width_field'),
        ),
    ]
