# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-31 03:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20160830_2055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wine',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='wine',
            new_name='product',
        ),
    ]
